### ISSUE TITLE
Output embedding dimension

### ISSUE THREAD

**Issue by jhyuklee** [hamed-zamani/snrm#1]
Hi, I'm a big fan of your work, and I have a question regarding the code.

In the paper, you used output layer of size [5k, 10k, 20k], which corresponds to the size of sparse vectors. But, in the code, all I see is `emb_dim = 100` in `params.py` and `snrm.py`.
It seems that `emb_dim` is used for both input and output embeddings (`get_embedding_params` and `get_embedding_layer_output`).
Could you explain the reason for this (relatively) small sized output vector?

Thank you.

**Comment by hamed-zamani** [comment]
Thanks for your interest. 

The `emb_dim` parameter just shows the word embedding dimensionality. The word embeddings are low-dimensional and dense. However, the query and document representations are high-dimensional and sparse. In more detail, `self.q_repr`, `self.d1_repr`, and `self.d2_repr` (look at `snrm.py`) are sparse with thousands of dimensions. 

I hope this helps.

**Comment by jhyuklee** [comment]
Then, it seems that the `layer_size` matters, which comes from `hidden_x` in the `params.py`.
But they are all set to -1, and should I adjust these as large as I want? (e.g., 10K for the last hidden layer)

**Comment by hamed-zamani** [comment]
Yes. For example, you can have three layers with dimensions of 500, 100, and 10000.

**Comment by jhyuklee** [comment]
Thank you for your kind replies. I'll close the issue.
