### ISSUE TITLE
Can not understand this sentence in paper, thank you!

### ISSUE THREAD

**Issue by guotong1988** [hamed-zamani/snrm#5]
![image](https://user-images.githubusercontent.com/4702353/63156020-5e121d80-c046-11e9-9990-50e148b9e66c.png)
@hamed-zamani

**Comment by hamed-zamani** [comment]
It is explained in Section 3.4 of the paper. I recommend you to take a look at an IR reference book to understand the concept of inverted indexing and their usage. Then these things become more clear. I hope this helps.
