### ISSUE TITLE
Why do the representaion have a lot of zero value?

### ISSUE THREAD

**Issue by guotong1988** [hamed-zamani/snrm#7]
![image](https://user-images.githubusercontent.com/4702353/63157386-6c156d80-c049-11e9-84e8-2354e839b685.png)
@hamed-zamani 
Thank you!

**Comment by hamed-zamani** [comment]
The representations have a lot of zero values, because we use a L1 loss on the learned representations, which makes them sparse. I hope this helps. (and by the way, sparsity is important for creating an inverted index for efficient retrieval)

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/63236553-b9275880-c270-11e9-96f1-2bf48a0f3fa0.png)
Thank you!
