### ISSUE TITLE
Robust and ClueWeb Training Data

### ISSUE THREAD

**Issue by YaaoTu** [hamed-zamani/snrm#8]
Hi Hamed,

Thanks a lot for your advanced work~ I plan to reproduce your paper. Could you please offer some ideas about how to get Robust and ClueWeb data except download from TREC... I don't find them in web..

Thanks a lot
Yaao

**Comment by hamed-zamani** [comment]
You have to purchase those datasets. They are not freely available for download. For example, the ClueWeb collection is part of the Lemur project and should be purchased.

**Comment by andrewyates** [comment]
In the case of robust04, I believe NIST has removed any restrictions on distributing it. You could extract the raw documents from the robust index [linked to in the Anserini Colab demo](https://colab.research.google.com/drive/1s44ylhEkXDzqNgkJSyXDYetGIxO9TWZn).
